spring.application.name=JobApp1.1

spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp

spring.datasource.url=jdbc:postgresql://localhost:5432/webapp
spring.datasource.username=postgres
spring.datasource.password=tiger
spring.datasource.driver-class-name=org.postgresql.Driver