spring.application.name=SpringJDBCPosgresDB

spring.datasource.url=jdbc:postgresql://localhost:5432/springbootjdbc
spring.datasource.username=postgres
spring.datasource.password=tiger
spring.datasource.driver-class-name=org.postgresql.Driver
